spring:
    datasource:
        url: jdbc:mysql://47.106.157.51:3306/teacher-manage?autoReconnect=true&useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 6000
        maxIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    cache:
      ehcache:
        config: ehcache.xml
      type: ehcache

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.weixin.heyawego.app.entity
    configuration:
              cache-enabled: true
              aggressive-lazy-loading: true
              log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
              lazy-loading-enabled: true
              multiple-result-sets-enabled: true
              use-column-label: true
              use-generated-keys: false
              auto-mapping-behavior: partial
              default-executor-type: simple
              map-underscore-to-camel-case: true
              local-cache-scope: session
              jdbc-type-for-null: null


server:
    port: 80
    context-path: /heyawego

